FROM caddy:latest as builder

RUN apk add --no-cache xcaddy go bash

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
